export enum MemoryQueryType {
  RECENT = 'RECENT',
  ENTITY = 'ENTITY',
  TIMELINE = 'TIMELINE',
  PREFERENCE = 'PREFERENCE',
  RELATIONSHIP = 'RELATIONSHIP',
  CONTEXT = 'CONTEXT',
  EVENT = 'EVENT',
  TEMPORARY = 'TEMPORARY',
  LONG_TERM = 'LONG_TERM',
  SEMANTIC = 'SEMANTIC',
}

export enum RankingSignalType {
  RECENCY = 'RECENCY',
  IMPORTANCE = 'IMPORTANCE',
  CONFIDENCE = 'CONFIDENCE',
  RELATIONSHIP_RELEVANCE = 'RELATIONSHIP_RELEVANCE',
  CONVERSATION_RELEVANCE = 'CONVERSATION_RELEVANCE',
  WORLD_RELEVANCE = 'WORLD_RELEVANCE',
  ENTITY_OVERLAP = 'ENTITY_OVERLAP',
  EXPIRY = 'EXPIRY',
  FRESHNESS = 'FRESHNESS',
  CONVERSATION_FREQUENCY = 'CONVERSATION_FREQUENCY',
}

export enum FilterType {
  MEMORY_TYPE = 'MEMORY_TYPE',
  DATE_RANGE = 'DATE_RANGE',
  IMPORTANCE = 'IMPORTANCE',
  CONFIDENCE = 'CONFIDENCE',
  EXPIRY_STATUS = 'EXPIRY_STATUS',
  RELATIONSHIP = 'RELATIONSHIP',
  TAG = 'TAG',
  ENTITY = 'ENTITY',
  SOURCE_EVENT = 'SOURCE_EVENT',
  VISIBILITY = 'VISIBILITY',
  ARCHIVED = 'ARCHIVED',
}

export enum QueryScope {
  IMMEDIATE = 'IMMEDIATE',
  RECENT = 'RECENT',
  CONTEXTUAL = 'CONTEXTUAL',
  HISTORICAL = 'HISTORICAL',
  FULL = 'FULL',
}

export enum RankingMode {
  STRICT = 'STRICT',
  BALANCED = 'BALANCED',
  PERMISSIVE = 'PERMISSIVE',
}
