export enum EventType {
  // User events
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',

  // Relationship events
  RELATIONSHIP_UPDATED = 'RELATIONSHIP_UPDATED',
  RELATIONSHIP_DIMENSION_CHANGED = 'RELATIONSHIP_DIMENSION_CHANGED',
  RELATIONSHIP_DIMENSIONS_BATCH_CHANGED = 'RELATIONSHIP_DIMENSIONS_BATCH_CHANGED',

  // Conversation events
  CONVERSATION_STARTED = 'CONVERSATION_STARTED',
  CONVERSATION_ENDED = 'CONVERSATION_ENDED',

  // Message events
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  MESSAGE_SENT = 'MESSAGE_SENT',

  // Memory events
  MEMORY_CREATED = 'MEMORY_CREATED',
  MEMORY_EXPIRED = 'MEMORY_EXPIRED',

  // Moment events
  MOMENT_TRIGGERED = 'MOMENT_TRIGGERED',

  // Notification events
  NOTIFICATION_SCHEDULED = 'NOTIFICATION_SCHEDULED',
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',

  // World events
  WORLD_GENERATED = 'WORLD_GENERATED',
  WORLD_UPDATED = 'WORLD_UPDATED',

  // Companion events
  COMPANION_CHANGED = 'COMPANION_CHANGED',
  COMPANION_STATE_CHANGED = 'COMPANION_STATE_CHANGED',

  // Interaction events
  INTERACTION_STARTED = 'INTERACTION_STARTED',
  INTERACTION_ENDED = 'INTERACTION_ENDED',

  // Prompt events
  PROMPT_BUILT = 'PROMPT_BUILT',

  // LLM events
  LLM_RESPONSE_GENERATED = 'LLM_RESPONSE_GENERATED',
}

export enum EventPriority {
  LOW = 0,
  NORMAL = 1,
  HIGH = 2,
  CRITICAL = 3,
}

export enum EventDispatchMode {
  SYNC = 'SYNC',
  ASYNC = 'ASYNC',
}

export enum EventStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
  DEAD_LETTERED = 'DEAD_LETTERED',
}

export enum AggregateType {
  USER = 'USER',
  RELATIONSHIP = 'RELATIONSHIP',
  CONVERSATION = 'CONVERSATION',
  MESSAGE = 'MESSAGE',
  MEMORY = 'MEMORY',
  MOMENT = 'MOMENT',
  NOTIFICATION = 'NOTIFICATION',
  WORLD = 'WORLD',
  COMPANION = 'COMPANION',
  INTERACTION = 'INTERACTION',
  PROMPT = 'PROMPT',
}
