export enum MemoryType {
  FACT = 'FACT',
  PREFERENCE = 'PREFERENCE',
  MILESTONE = 'MILESTONE',
  EVENT = 'EVENT',
  EMOTION = 'EMOTION',
  RELATIONSHIP = 'RELATIONSHIP',
}

export enum MemoryImportance {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum MemoryExpiry {
  PERMANENT = 'PERMANENT',
  LONG_TERM = 'LONG_TERM',
  MEDIUM_TERM = 'MEDIUM_TERM',
  SHORT_TERM = 'SHORT_TERM',
  EPHEMERAL = 'EPHEMERAL',
}

export enum MemoryCategory {
  USER_PROFILE = 'USER_PROFILE',
  PREFERENCES = 'PREFERENCES',
  HABITS = 'HABITS',
  RELATIONSHIPS = 'RELATIONSHIPS',
  MILESTONES = 'MILESTONES',
  CONVERSATIONS = 'CONVERSATIONS',
  EXPERIENCES = 'EXPERIENCES',
  EMOTIONS = 'EMOTIONS',
}
