export enum ResponseProcessingStatus {
  RECEIVED = 'RECEIVED',
  PARSED = 'PARSED',
  VALIDATED = 'VALIDATED',
  ENRICHED = 'ENRICHED',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
}

export enum ResponseValidationSeverity {
  BLOCKING = 'BLOCKING',
  WARNING = 'WARNING',
  INFO = 'INFO',
}

export enum SafetyCategory {
  SELF_HARM = 'SELF_HARM',
  VIOLENCE = 'VIOLENCE',
  HATE = 'HATE',
  SEXUAL = 'SEXUAL',
  ILLEGAL = 'ILLEGAL',
  PRIVACY_LEAK = 'PRIVACY_LEAK',
  MEDICAL_ADVICE = 'MEDICAL_ADVICE',
  LEGAL_ADVICE = 'LEGAL_ADVICE',
  FINANCIAL_ADVICE = 'FINANCIAL_ADVICE',
}

export enum DetectionKind {
  FOLLOW_UP = 'FOLLOW_UP',
  REMINDER = 'REMINDER',
  MEMORY_CANDIDATE = 'MEMORY_CANDIDATE',
  RELATIONSHIP_UPDATE = 'RELATIONSHIP_UPDATE',
  NOTIFICATION_CANDIDATE = 'NOTIFICATION_CANDIDATE',
  MOMENT_CANDIDATE = 'MOMENT_CANDIDATE',
}

export enum ResponseFormat {
  PLAIN_TEXT = 'PLAIN_TEXT',
  JSON = 'JSON',
  MARKDOWN = 'MARKDOWN',
  TOOL_CALL = 'TOOL_CALL',
}
