export enum MomentKind {
  MILESTONE = 'MILESTONE',
  ANNIVERSARY = 'ANNIVERSARY',
  CALLBACK = 'CALLBACK',
  FOLLOW_UP = 'FOLLOW_UP',
  REMINDER = 'REMINDER',
  CELEBRATION = 'CELEBRATION',
  REFLECTION = 'REFLECTION',
  CHECK_IN = 'CHECK_IN',
  EMOTIONAL_SUPPORT = 'EMOTIONAL_SUPPORT',
  SHARED_INTEREST = 'SHARED_INTEREST',
}

export enum MomentTrigger {
  MEMORY_CREATED = 'MEMORY_CREATED',
  RELATIONSHIP_UPDATED = 'RELATIONSHIP_UPDATED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  CONVERSATION_ENDED = 'CONVERSATION_ENDED',
  SCHEDULE_ELAPSED = 'SCHEDULE_ELAPSED',
  MANUAL = 'MANUAL',
}

export enum MomentSignificance {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  MILESTONE = 'MILESTONE',
}

export enum MomentStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  DELIVERED = 'DELIVERED',
  DISMISSED = 'DISMISSED',
  EXPIRED = 'EXPIRED',
}
